[[server]]
name = "app-stacks"
[server.config]
enabled = true

##

[[server]]
name = "caddy"
[server.config]
enabled = true

##

[[stack]]
name = "caddy"
[stack.config]
server = "caddy"
auto_update = true
auto_update_all_services = true
linked_repo = "docker"
run_directory = "stacks/caddy"
file_paths = ["compose.yaml"]
environment = """
UPLOAD_TOKEN=[[UPLOAD_TOKEN]]
"""

##

[[stack]]
name = "channels-addons"
[stack.config]
server = "app-stacks"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
linked_repo = "docker"
run_directory = "stacks/channels-addons"
file_paths = ["compose.yaml"]
environment = """
MLB_USERNAME=[[MLB_USERNAME]]
MLB_PASSWORD=[[MLB_PASSWORD]]
"""

##

[[stack]]
name = "channels2mqtt"
[stack.config]
server = "app-stacks"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
linked_repo = "docker"
run_directory = "stacks/channels2mqtt"
file_paths = ["compose.yaml"]
environment = """
HA_USERNAME=[[HA_USERNAME]]
HA_PASSWORD=[[HA_PASSWORD]]
"""

##

[[stack]]
name = "container-backup-caddy"
[stack.config]
server = "caddy"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
linked_repo = "docker"
run_directory = "stacks/container-backup-caddy"
file_paths = ["compose.yaml"]

##

[[stack]]
name = "container-backup-core"
[stack.config]
server = "app-stacks"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
linked_repo = "docker"
run_directory = "stacks/container-backup-core"
file_paths = ["compose.yaml"]

##

[[stack]]
name = "ecobeealerts2mqtt"
[stack.config]
server = "app-stacks"
auto_update = true
auto_update_all_services = true
linked_repo = "docker"
run_directory = "stacks/ecobeealerts2mqtt"
file_paths = ["compose.yaml"]
environment = """
HA_USERNAME=[[HA_USERNAME]]
HA_PASSWORD=[[HA_PASSWORD]]
"""

##

[[stack]]
name = "homepage"
[stack.config]
server = "app-stacks"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_provider = "GitHub.com"
git_account = "zackwag"
repo = "zackwag/docker"
file_paths = ["stacks/homepage/compose.yaml"]

##

[[stack]]
name = "it-tools"
[stack.config]
server = "app-stacks"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
linked_repo = "docker"
run_directory = "stacks/it-tools"
file_paths = ["compose.yaml"]

##

[[stack]]
name = "radio"
[stack.config]
server = "app-stacks"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
linked_repo = "docker"
run_directory = "stacks/radio"
file_paths = ["compose.yaml"]

##

[[stack]]
name = "retroarch-webdav"
[stack.config]
server = "app-stacks"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
linked_repo = "docker"
run_directory = "stacks/retroarch-webdav"
file_paths = ["compose.yaml"]
environment = """
WEBDAV_RETROARCH_USER=[[WEBDAV_RETROARCH_USER]]  # VARIABLE = value
WEBDAV_RETROARCH_PASSWORD=[[WEBDAV_RETROARCH_PASSWORD]]
"""

##

[[stack]]
name = "samba"
[stack.config]
server = "app-stacks"
git_provider = "GitHub.com"
git_account = "zackwag"
repo = "zackwag/docker"
file_paths = ["stacks/samba/compose.yaml"]
environment = """
SAMBA_ADMIN_USER=[[SAMBA_ADMIN_USER]]
SAMBA_ADMIN_PASSWORD=[[SAMBA_ADMIN_PASSWORD]]
SAMBA_RETROARCH_USER=[[SAMBA_RETROARCH_USER]]
SAMBA_RETROARCH_PASSWORD=[[SAMBA_RETROARCH_PASSWORD]]
"""

##

[[stack]]
name = "slash"
[stack.config]
server = "app-stacks"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
linked_repo = "docker"
run_directory = "stacks/slash"
file_paths = ["compose.yaml"]

##

[[stack]]
name = "transfersh"
[stack.config]
server = "app-stacks"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
linked_repo = "docker"
run_directory = "stacks/transfersh"
file_paths = ["compose.yaml"]

##

[[stack]]
name = "writefreely"
[stack.config]
server = "app-stacks"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
linked_repo = "docker"
run_directory = "stacks/writefreely"
file_paths = ["compose.yaml"]

##

[[repo]]
name = "docker"
[repo.config]
git_account = "zackwag"
repo = "zackwag/docker"

##

[[procedure]]
name = "Auto Sync"
config.schedule = "Every day at midnight"

[[procedure.config.stage]]
name = "Stage 1"
enabled = true
executions = [
  { execution.type = "RunSync", execution.params.sync = "docker", enabled = true }
]

##

[[procedure]]
name = "Backup Core Database"
description = "Triggers the Core database backup at the scheduled time."
tags = ["system"]
config.schedule = "Every day at 01:00"

[[procedure.config.stage]]
name = "Stage 1"
enabled = true
executions = [
  { execution.type = "BackupCoreDatabase", execution.params = {}, enabled = true }
]

##

[[procedure]]
name = "Global Auto Update"
description = "Pulls and auto updates Stacks and Deployments using 'poll_for_updates' or 'auto_update'."
tags = ["system"]
config.schedule = "Every day at 05:00"

[[procedure.config.stage]]
name = "Stage 1"
enabled = true
executions = [
  { execution.type = "GlobalAutoUpdate", execution.params.skip_auto_update = false, enabled = true }
]

##

[[procedure]]
name = "Rotate Server Keys"
description = "Rotates all currently connected Server keys."
tags = ["system"]
config.schedule = "Every day at 06:00"

[[procedure.config.stage]]
name = "Stage 1"
enabled = true
executions = [
  { execution.type = "RotateAllServerKeys", execution.params = {}, enabled = true }
]

##

[[alerter]]
name = "Home Assistant"
[alerter.config]
enabled = true
endpoint.type = "Custom"
endpoint.params.url = "http://192.168.4.90:8123/api/webhook/-jzw7PvzlmF6pCfUToOqFsu8d"
alert_types = [
  "ServerUnreachable",
  "ServerCpu",
  "ServerMem",
  "ServerDisk",
  "StackStateChange",
  "ContainerStateChange",
  "BuildFailed",
  "RepoBuildFailed",
  "ActionFailed",
  "ProcedureFailed"
]

##

[[builder]]
name = "Local"
[builder.config]
type = "Server"
params.server = "app-stacks"

##

[[resource_sync]]
name = "docker"
[resource_sync.config]
linked_repo = "docker"
resource_path = ["komodo/resources.toml"]
managed = true