services:
  samba:
    image: dperson/samba
    container_name: samba
    restart: unless-stopped
    ports:
      - "139:139"
      - "445:445"
    environment:
      - USER=${SAMBA_RETROARCH_USER};${SAMBA_RETROARCH_PASSWORD}
      - USER2=${SAMBA_ADMIN_USER};${SAMBA_ADMIN_PASSWORD}
      - SHARE=retroarch;/share/retroarch;yes;no;no;${SAMBA_RETROARCH_USER}
      - SHARE2=data;/share;yes;no;no;${SAMBA_ADMIN_USER}
      - WORKGROUP=WORKGROUP
    volumes:
      - /docker/samba/data:/share