services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - /docker/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped
networks: {}
