services:
  nut2mqtt:
    image: zackwag/nut2mqtt:latest
    container_name: nut2mqtt
    restart: unless-stopped
    init: true
    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - /docker/nut2mqtt/nut:/etc/nut:ro
      - /docker/nut2mqtt/config/config.yaml:/data/config.yaml:ro
      - /docker/nut2mqtt/data:/data
      - /dev/bus/usb:/dev/bus/usb