services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    network_mode: host
    restart: unless-stopped
    environment:
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_NOTIFICATIONS: email
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: zackwag@gmail.com
      WATCHTOWER_NOTIFICATION_EMAIL_TO: zackwag@gmail.com
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: smtp.gmail.com
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: 587
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: zackwag@gmail.com
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: REDACTED
      WATCHTOWER_NOTIFICATION_EMAIL_DELAY: 30
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks: {}
