services:
  mqtt-explorer:
    image: smeagolworms4/mqtt-explorer:latest
    container_name: mqtt-explorer
    ports:
      - "4321:4000"
    volumes:
      - /docker/mqtt-explorer/data:/data
    restart: unless-stopped