services:
  mqtt-explorer:
    image: ghcr.io/thomasnordquist/mqtt-explorer:latest
    container_name: mqtt-explorer
    restart: unless-stopped
    ports:
      - "4321:3000"
    environment:
      - MQTT_EXPLORER_SKIP_AUTH=true
    volumes:
      - /docker/mqtt-explorer/data:/app/data
