services:
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    hostname: freshrss
    restart: unless-stopped
    ports:
      - 9061:80
    logging:
      options:
        max-size: 10m
    volumes:
      - /docker/freshrss/data:/var/www/FreshRSS/data
      - /docker/freshrss/extensions:/var/www/FreshRSS/extensions
    environment:
      TZ: America/New_York
      CRON_MIN: 25,55
      TRUSTED_PROXY: 172.16.0.1/12 192.168.0.1/16
networks: {}
