services:
  write-freely:
    image: nephatrine/write-freely:latest
    container_name: write-freely
    restart: unless-stopped
    environment:
      TZ: America/New_York
      PUID: 1000
      PGID: 1000
    ports:
      - 70:70/tcp
      - 8250:8080/tcp
    volumes:
      - /docker/writefreely:/mnt/config
networks: {}
