services:
  container-backup-caddy:
    image: zackwag/flask-container-backup:latest
    container_name: container-backup-caddy
    restart: unless-stopped
    ports:
      - 2128:2128
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /docker/container-backup-caddy/config:/app/config
      - /docker:/source
      - onedrive:/destination
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=America/New_York
      - MODE=spoke
networks: {}
volumes:
  onedrive:
    driver: rclone
    driver_opts:
      remote: Onedrive:/backup
